name: Actividad04 - Publish Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test and collect coverage
        run: |
          dotnet test EcommerceApp/EcommerceApp.Tests/EcommerceApp.Tests.csproj \
            --collect:"XPlat Code Coverage" \
            --results-directory coverage \
            --logger trx

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator \
            -reports:coverage/**/coverage.cobertura.xml \
            -targetdir:EcommerceApp/Cobertura \
            -reporttypes:Html
        env:
          PATH: $PATH:/home/runner/.dotnet/tools

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-report
          path: EcommerceApp/Cobertura

  deploy:
    needs: build-test-coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cobertura-report
          path: ./Cobertura

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Cobertura
        keep_files: true
